version: '3.2'
services:
  teamspeak:
    container_name: teamspeak
    image: linuxserver/gsm-ts3
    restart: unless-stopped
    network_mode: host
    ports:
    - "9987:9987/udp"
    - "30033:30033"
    - "10011:10011"
    - "41144:41144"
    volumes:
    - /docker/teamspeak:/config
