version: '3.2'
services:
  teamspeak:
    container_name: teamspeak
    image: teamspeak
    restart: unless-stopped
    environment:
      TS3SERVER_LICENSE: accept
    ports:
    - "9987:9987/udp"
    - "30033:30033"
    - "10011:10011"
    volumes:
    - /docker/teamspeak/:/var/ts3server/
