#!/bin/sh
#
#    00-header - create the header of the MOTD
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

IP="$(hostname -I)"
FIGLET="$(figlet -w 92 -f small Server.DODEKERACT.coM)"
DISTRIBUTION="$DISTRIB_DESCRIPTION ($(uname -o) $(uname -r) $(uname -m))"

printf "\033[32m$FIGLET\033[0m\n"
printf "          IP: $(hostname -I)\n"
printf "Distribution: $DISTRIBUTION\n"
printf "      Uptime:$(uptime)\n"

#printf "              .-.\n"
#printf "        .-'\`\`(|||)\n"
#printf "     ,\`\\ \\    \`-\`.             88                         88\n"
#printf "    /   \\ '\`\`-.   \`            88                         88\n"
#printf "  .-.  ,       \`___:  88   88  88,888,  88   88  ,88888, 88888  88   88\n"
#printf " (:::) :        ___   88   88  88   88  88   88  88   88  88    88   88\n"
#printf "  \`-\`  \`       ,   :  88   88  88   88  88   88  88   88  88    88   88\n"
#printf "    \\   / ,..-\`   ,   88   88  88   88  88   88  88   88  88    88   88\n"
#printf "     \`./ /    .-.\`    '88888'  '88888'  '88888'  88   88  '8888 '88888'\n"
#printf "        \`-..-(   )    $DISTRIBUTION\n"
#printf "              \`-\`\n"

DOCKER=$(docker ps -a --format "table {{.Status}}\t{{.Names}}\t{{.Image}}")

printf "\n"
printf "$DOCKER"
