version: '3.2'
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
    - "25565:25565"
    volumes:
    - /docker/minecraft:/data
    environment:
    - EULA=true
    - MEMORY=12G
    - TYPE=PAPER
    stdin_open: true
    tty: true
