version: '3.2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: dodekeract.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "10024:10024"
    volumes:
      - /docker/mail/data/:/var/mail
      - /docker/mail/config/:/tmp/docker-mailserver
      - /docker/letsencrypt/storage:/etc/letsencrypt
      - /docker/mail/state/:/var/mail-state
    environment:
      - SSL_TYPE=letsencrypt
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
