version: '3.2'
services:
  caddy:
    build: .
    environment:
    - CLOUDFLARE_API_TOKEN=CENSORED
    network_mode: host
    restart: unless-stopped
    ports:
    - 443
    - 80
    volumes:
    - /docker/caddy/static/:/var/www/:ro,cached
    - /docker/caddy/caddy.json:/caddy.json:ro,cached
    - /docker/caddy/data/:/data/
    - /docker/caddy/config/:/config/
