version: '3.2'
services:
  caddy:
    container_name: caddy
    network_mode: host
    image: abiosoft/caddy
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - type: volume
      source: /docker/caddy/static
      target: /srv
    - type: volume
      source: /docker/caddy/cache
      target: /root/.caddy
    - type: volume
      source: /docker/caddy/Caddyfile
      target: /etc/Caddyfile
